name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with: {python-version: 3.9}

    - name: Install deps
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest -v tests/

    - name: Build Docker
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
